#!/usr/bin/env bash
# zeos-optane installer — works on any modern Linux (no Zeos required).
#
# Installs:
#   /usr/local/lib/zeos-optane/zeos_optane/        Python package
#   /usr/local/bin/zeos-optane                     CLI shim (python3 -m zeos_optane)
#   /etc/systemd/system/zeos-optane-detect.service Boot-time detection check
#   /etc/udev/rules.d/99-zeos-optane.rules         Hot-plug detection trigger
#   /etc/zeos/                                     Config directory (skeleton)
#
# Re-running this is safe: existing files are replaced, the service is
# re-enabled, udev rules are reloaded. Use ./uninstall.sh to reverse.

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "error: install.sh must run as root (try: sudo $0)" >&2
    exit 1
fi

PYTHON="${PYTHON:-python3}"
if ! command -v "$PYTHON" >/dev/null 2>&1; then
    echo "error: python3 not found in PATH" >&2
    exit 1
fi

PY_VER="$("$PYTHON" -c 'import sys; print("%d.%d" % sys.version_info[:2])')"
PY_MAJOR="${PY_VER%%.*}"
PY_MINOR="${PY_VER##*.}"
if (( PY_MAJOR < 3 || (PY_MAJOR == 3 && PY_MINOR < 9) )); then
    echo "error: python >= 3.9 required (found $PY_VER)" >&2
    exit 1
fi

# Resolve the directory containing this script (works even via symlink).
SRC_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"

INSTALL_LIB="/usr/local/lib/zeos-optane"
INSTALL_BIN="/usr/local/bin/zeos-optane"
SYSTEMD_DIR="/etc/systemd/system"
UDEV_DIR="/etc/udev/rules.d"
CONFIG_DIR="/etc/zeos"

echo ">> installing zeos-optane (source: $SRC_DIR)"

# --- Python package ---------------------------------------------------------
mkdir -p "$INSTALL_LIB"
rm -rf "$INSTALL_LIB/zeos_optane"
cp -r "$SRC_DIR/zeos_optane" "$INSTALL_LIB/zeos_optane"
echo "   * package -> $INSTALL_LIB/zeos_optane"

# --- CLI shim ---------------------------------------------------------------
cat > "$INSTALL_BIN" <<EOF
#!/usr/bin/env bash
# zeos-optane shim. Generated by install.sh — do not edit.
exec $PYTHON -P -c 'import sys; sys.path.insert(0, "$INSTALL_LIB"); from zeos_optane.cli import main; raise SystemExit(main())' "\$@"
EOF
chmod 0755 "$INSTALL_BIN"
echo "   * cli     -> $INSTALL_BIN"

# --- Config directory -------------------------------------------------------
mkdir -p "$CONFIG_DIR/specs"
chmod 0755 "$CONFIG_DIR" "$CONFIG_DIR/specs"
echo "   * config  -> $CONFIG_DIR/"

# --- systemd unit -----------------------------------------------------------
install -m 0644 "$SRC_DIR/systemd/zeos-optane-detect.service" "$SYSTEMD_DIR/zeos-optane-detect.service"
echo "   * systemd -> $SYSTEMD_DIR/zeos-optane-detect.service"

# --- udev rule --------------------------------------------------------------
install -m 0644 "$SRC_DIR/udev/99-zeos-optane.rules" "$UDEV_DIR/99-zeos-optane.rules"
echo "   * udev    -> $UDEV_DIR/99-zeos-optane.rules"

# --- Activate ---------------------------------------------------------------
if command -v systemctl >/dev/null 2>&1 && [[ -d /run/systemd/system ]]; then
    systemctl daemon-reload
    systemctl enable zeos-optane-detect.service >/dev/null
    echo "   * enabled zeos-optane-detect.service"
else
    echo "   * systemd not active; skipping enable (run manually if/when present)"
fi
if command -v udevadm >/dev/null 2>&1; then
    udevadm control --reload-rules || true
    udevadm trigger --subsystem-match=block --action=add || true
    echo "   * reloaded udev rules"
fi

cat <<'POST'

zeos-optane installed.

Next steps:
    sudo zeos-optane scan         # see what's detected
    sudo zeos-optane configure    # interactive: place each device into its role

Persistent state is at:
    /etc/zeos/optane.json         # canonical config (Zeos-native schema)
    /etc/zeos/specs/optane-*.json # per-device signal contracts

Both are read by Zeos kernel native at boot when it ships, so the
configuration carries forward without re-running this tool.
POST
