#!/usr/bin/env python3
# Rasterize the mapped cursor SVGs to embedded RGBA sprites for the kernel.
# White fill + dark outline (visible on any background), alpha-antialiased.
# Emits os/boot/cursor_sprites.h aligned to cursor_state_t order.
import os, subprocess, sys
from PIL import Image, ImageFilter

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SVG  = os.path.join(REPO, "assets/icons/cursors")
OUT  = os.path.join(REPO, "os/boot/cursor_sprites.h")
SZ   = 24                      # sprite is SZ x SZ
WHITE = (0xF5, 0xF8, 0xFF)
DARK  = (0x0D, 0x11, 0x17)

# (enum name, svg number, hotspot kind) in cursor_state_t order.
CENTER = {"TEXT","CROSSHAIR","MOVE","WAIT","DRAG"}
STATES = [
    ("CURSOR_DEFAULT","032"),("CURSOR_CLICK","016"),("CURSOR_CLICK_BURST","013"),
    ("CURSOR_CLICK_CONFIRM","009"),("CURSOR_POINTER","050"),("CURSOR_TEXT","036"),
    ("CURSOR_CROSSHAIR","047"),("CURSOR_MOVE","048"),("CURSOR_RESIZE_DIAG","042"),
    ("CURSOR_GRAB","050"),("CURSOR_ADD","006"),("CURSOR_REMOVE","007"),
    ("CURSOR_DELETE","008"),("CURSOR_FORBIDDEN","020"),("CURSOR_HELP","015"),
    ("CURSOR_BUSY","025"),("CURSOR_WAIT","040"),("CURSOR_LOADING","011"),
    ("CURSOR_PROGRESS","003"),("CURSOR_SELECT","012"),("CURSOR_ALERT","014"),
    ("CURSOR_DRAG","004"),
]

def raster(num):
    src = os.path.join(SVG, f"{num}-cursor.svg")
    png = f"/tmp/_cur_{num}.png"
    subprocess.run(["rsvg-convert","-w",str(SZ),"-h",str(SZ),src,"-o",png],check=True)
    return Image.open(png).convert("RGBA")

def build(img, key):
    a = img.split()[3]                          # shape alpha (mask)
    dil = a.filter(ImageFilter.MaxFilter(3))    # 1px dilation -> outline ring
    px_a, px_d = a.load(), dil.load()
    out = Image.new("RGBA",(SZ,SZ),(0,0,0,0)); po = out.load()
    hx=hy=0; best=10**9
    for y in range(SZ):
        for x in range(SZ):
            ca, da = px_a[x,y], px_d[x,y]
            if ca > 40:
                po[x,y]=(WHITE[0],WHITE[1],WHITE[2],ca)          # white core
            elif da > 40:
                po[x,y]=(DARK[0],DARK[1],DARK[2],da)             # dark outline
            if ca > 128 and (x+y) < best:                        # tip = nearest corner
                best=x+y; hx,hy=x,y
    if key in CENTER: hx=hy=SZ//2
    return out, hx, hy

def main():
    with open(OUT,"w") as f:
        f.write("/* AUTO-GENERATED by tools/gen_cursors.py -- do not edit. */\n")
        f.write("#pragma once\n#include <stdint.h>\n")
        f.write(f"#define CURSOR_SPR_SZ {SZ}\n\n")
        f.write(f"static const uint32_t cursor_sprites[{len(STATES)}][{SZ*SZ}] = {{\n")
        hotspots=[]
        for name,num in STATES:
            key=name.replace("CURSOR_","")
            spr,hx,hy = build(raster(num), key)
            hotspots.append((hx,hy))
            f.write(f"  /* {name} <- {num} */ {{")
            px=spr.load()
            vals=[]
            for y in range(SZ):
                for x in range(SZ):
                    r,g,b,al=px[x,y]
                    vals.append(f"0x{al:02x}{r:02x}{g:02x}{b:02x}")
            f.write(",".join(vals)); f.write("},\n")
        f.write("};\n\n")
        f.write(f"static const int cursor_hotspot[{len(STATES)}][2] = {{")
        f.write(",".join(f"{{{hx},{hy}}}" for hx,hy in hotspots))
        f.write("};\n")
    print("wrote", OUT, "states:", len(STATES))

main()
